# travis-ci.org

language: ruby
rvm:
- 2.4

script: bundle exec jekyll build && bundle exec htmlproofer --timeframe 30d --only-4xx ./_site

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change
