# travis-ci.org

language: ruby
rvm:
- 2.4

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/.jekyll-cache

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change
