language: ruby
rvm:
  - 2.6

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - JEKYLL_ENV=production

# install:
#   - bundle install
# script:
#   - rake

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/.jekyll-cache

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
