# travis-ci.org

language: ruby
rvm:
- 2.3.3

install: gem install jekyll html-proofer
script: jekyll build && htmlproofer --timeframe 30d ./_site

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache:
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change
