name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Build GitHub Pages
        env:
          JEKYLL_ENV: production
          LC_ALL: C.UTF-8
        run: |
          bundle exec jekyll build --destination=./_site
      - name: Upload GitHub Pages to artifact
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: _site
